version: "3.8"

services:
  server:
    build: server/
    command: python ./server.py
    ports:
      - 3000:3000
    healthcheck:
      test: [ "CMD", "curl", "-f", "http://localhost:3000" ]
      interval: 10s
      retries: 5
    networks:
      - server_net

  client:
    build: client/
    command: python ./client.py
    depends_on:
      server:
        condition: service_healthy
    network_mode: host
    environment:
      - DEBUG=True
    networks:
      - client_net

networks:
  server_net:
    driver: bridge
  client_net:
    driver: bridge
